collections:
  photos:
google_analytics: UA-162614325-1
title: SPHT
# email: contact@spht.cl
description: >- 
  Personal website where I'll upload photographs I take, along with anecdotes and other stuff when I have the time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spht.cl" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: sebaarrr
#github_username:  sushift
#instagram_username: sebaa.sch
minima:
  skin: dark

  social_links:
    twitter: sebaarrr
    instagram: sebaa.sch
    github: sushift

# Build settings
#remote_theme: broccolini/swiss
theme: minima

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
