# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  photos:
google_analytics: UA-162614325-1
title: SPHT
# email: contact@spht.cl
description: >- 
  Personal website where I'll upload photographs I take, along with anecdotes and other stuff when I have the time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spht.cl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sebaarrr
github_username:  sushift
instagram_username: sebaa.sch